export const APIStatus = {
    OK: "OK",
    NOT_FOUND:"NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    AUTHENTICATE:"AUTHENTICATE",
    DB_ERROR:"DB_ERROR",
    INVALID_INPUT:"INVALID_INPUT",
    EXISTED:"EXISTED"
}

export const HTTPMethod = {
    GET:"GET",
    POST: "POST",
    PUT: "PUT",
    DELETE: "DELETE"
}